package report

import (
	"bytes"
	"fmt"
	"html/template"
	"time"
)

// Data is everything a report shows. Built from a run's archive, so a report
// can be produced long after the run finished and regenerated later with
// improvements — which is why generation is on demand rather than baked at run
// end.
type Data struct {
	// Identity.
	RunID    string
	Name     string
	Kind     string
	State    string
	Started  time.Time
	Ended    time.Time
	Duration time.Duration
	Err      string
	// Version of the ORBIT that rendered this, so an old report is not read as
	// though it came from today's build.
	Version    string
	Generated  time.Time
	SourceHost string

	// Headline figures, as label/value pairs so a kind can contribute its own
	// without the template knowing about run kinds.
	Headline []KV

	// Configuration, verbatim (credentials removed upstream).
	ConfigLabel string
	Config      string

	// Charts over the run's retained series.
	Charts []Chart

	// Tables of the raw numbers, so the data is extractable rather than only
	// pictured — a report that cannot be read back into a spreadsheet is a
	// screenshot with extra steps.
	Tables []Table

	// The run's narrative.
	Events []Event

	// Notes are caveats that belong with the numbers rather than in a footnote
	// — a report is read by someone who was not watching, so anything that
	// would mislead them has to travel with it.
	Notes []string
}

// KV is a labelled value, optionally with a subordinate detail.
type KV struct {
	Label  string
	Value  string
	Detail string
}

// Table is a titled grid.
type Table struct {
	Title   string
	Columns []string
	Rows    [][]string
	// Note explains what the table does or does not cover.
	Note string
}

// Event is one line of the run's event log.
type Event struct {
	At       string
	Severity string
	Kind     string
	Subject  string
	Message  string
}

// HasFailure reports whether the run ended badly, which drives the banner.
func (d Data) HasFailure() bool {
	return d.State == "FAILED" || d.State == "CANCELLED" || d.Err != ""
}

// StatusTone maps the run state onto a banner class.
func (d Data) StatusTone() string {
	switch d.State {
	case "COMPLETE":
		return "ok"
	case "FAILED":
		return "bad"
	case "CANCELLED":
		return "warn"
	default:
		return "neutral"
	}
}

// FormatDuration renders a duration for a reader rather than for a parser.
func FormatDuration(d time.Duration) string {
	if d <= 0 {
		return "—"
	}
	if d < time.Minute {
		return fmt.Sprintf("%.1fs", d.Seconds())
	}
	m := int(d.Minutes())
	s := int(d.Seconds()) - m*60
	if m < 60 {
		return fmt.Sprintf("%dm %02ds", m, s)
	}
	return fmt.Sprintf("%dh %02dm %02ds", m/60, m%60, s)
}

var tmpl = template.Must(template.New("report").Funcs(template.FuncMap{
	"safeSVG": func(s string) template.HTML { return template.HTML(s) }, //nolint:gosec // generated by chart.go, not user input
	"stamp":   func(t time.Time) string { return t.Format("2006-01-02 15:04:05 MST") },
}).Parse(documentHTML))

// HTML renders the report as a single self-contained document.
func HTML(d Data) ([]byte, error) {
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, d); err != nil {
		return nil, fmt.Errorf("render report: %w", err)
	}
	return buf.Bytes(), nil
}
